spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mississippi.cn6qj3gf4bmy.ap-northeast-2.rds.amazonaws.com:3306/
    username: mssp
    password: mssp1234

  jpa:
    hibernate:
    properties:
      hibernate:
        format_sql: true

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  # 서버에 사진이 저장됨, 경로
  file:
    path: /home/ec2-user/image

logging:
  level:
    org.hibernate.SQL: debug

kakao:
  request:
    url:
      token: https://kauth.kakao.com/oauth/token
      userInfo: https://kapi.kakao.com/v2/user/me
  clientId : 39b1629ce319fa9f89c3b9f947d92255
  redirectUri : http://43.200.115.73:8080/oauth
